apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: keycloak
  name: keycloak
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: keycloak
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: keycloak
    serviceAccount: keycloak
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-keycloak-postgres
  namespace: keycloak
spec:
  type: kv-v2
  mount: keycloak
  path: postgres
  destination:
    name: postgres-credentials
    create: true
    overwrite: true
  refreshAfter: 30s
  vaultAuthRef: static-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-keycloak-admin
  namespace: keycloak
spec:
  type: kv-v2
  mount: keycloak
  path: keycloak-admin
  destination:
    name: keycloak-admin-secret
    create: true
    overwrite: true
  refreshAfter: 30s
  vaultAuthRef: static-auth