APPLICATIONS:
  GLOBAL:
    BASE_URL: example.com
  GITEA:
    ADMIN:
      USERNAME: example
      PASSWORD: example
  GRAFANA:
    HEADER_VALUE: example
  CERT_MANAGER:
    ORG: example
  PGADMIN:
    DEFAULT:
      EMAIL: example
      PASSWORD: example