APPLICATIONS:
  GLOBAL:
    BASE_URL: example
    MICROK8S: "false"
  ISTIO:
    AMBIENT: "false"
  GITEA:
    ADMIN:
      USERNAME: example
      PASSWORD: example
  GRAFANA:
    HEADER_VALUE: example
  CERT_MANAGER:
    ORG: example
  PGADMIN:
    DEFAULT:
      EMAIL: example
      PASSWORD: example