apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    name: prometheus
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    name: grafana
    istio.io/dataplane-mode: ambient
