apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openproject
  namespace: openproject
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: Gateway	
      name: infra-gateway
      namespace: istio-system
  hostnames:
    - openproject.${APPLICATIONS.GLOBAL.BASE_URL}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
       - kind: Service	
         name: openproject
         port: 8080
         weight: 100
         group: ''
