apiVersion: batch/v1
kind: CronJob
metadata:
  name: telemetrygen-traces
  namespace: telemetrygen
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: telemetrygen-traces
              image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
              imagePullPolicy: IfNotPresent
              args:
                - 'traces'
                - '--otlp-insecure'
                - '--duration'
                - '1s'
                - '--rate'
                - '5.0'
                - '--otlp-endpoint'
                - 'grafana-alloy.alloy.svc.cluster.local:4317'
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: telemetrygen-metrics
  namespace: telemetrygen
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: telemetrygen-metrics
              image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
              imagePullPolicy: IfNotPresent
              args:
                - 'metrics'
                - '--duration'
                - '45s'
                - '--rate'
                - '1.0'
                - '--otlp-insecure'
                - '--otlp-endpoint'
                - 'grafana-alloy.alloy.svc.cluster.local:4317'
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: telemetrygen-logs
  namespace: telemetrygen
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: telemetrygen-logs
              image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
              imagePullPolicy: IfNotPresent
              args:
                - 'logs'
                - '--duration'
                - '1s'
                - '--rate'
                - '5.0'
                - '--otlp-insecure'
                - '--otlp-endpoint'
                - 'grafana-alloy.alloy.svc.cluster.local:4317'
          restartPolicy: OnFailure