grafana:
  grafana.ini:
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_role: Admin
  namespaceOverride: grafana
  additionalDataSources:
    - name: loki
      basicAuth: false
      editable: true
      type: loki
      url: http://loki.loki.svc.cluster.local:3100
      jsonData:
        httpHeaderName1: 'X-Scope-OrgID'
      secureJsonData:
        httpHeaderValue1: '${APPLICATIONS.GRAFANA.HEADER_VALUE}'
    - name: tempo
      basicAuth: false
      editable: true
      type: tempo
      url: http://tempo.tempo.svc.cluster.local:3100
      jsonData:
        httpMethod: GET
        tracesToLogsV2:
          datasourceUid: 'loki'
          spanStartTimeShift: '-10m'
          spanEndTimeShift: '10m'
          tags: [{key: 'job', value: 'job'}]
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: '{$${__tags}} |="$${__span.traceId}"'
        tracesToMetrics:
          datasourceUid: 'prometheus'
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
          tags: [{key: 'service.name', value: 'service'}, {key: 'job'}]
          queries:
            - name: 'Sample Query'
              query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}