apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: prometheus
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: Gateway	
      name: infra-gateway
      namespace: istio-system
  hostnames:
    - prometheus.${APPLICATIONS.GLOBAL.BASE_URL}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-kube-prometheus-prometheus
          kind: Service
          port: 9090
          weight: 1
          group: ''