apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: infra-project
  sources:
  - repoURL: "https://dl.gitea.com/charts/"
    chart: "gitea"
    targetRevision: 10.6.0  # Specify the version of the Helm chart
    helm:
      values: |
        gitea:
          admin:
            existingSecret: gitea-admin-secret
          config:
            server:
              ROOT_URL: https://gitea.${APPLICATIONS.GLOBAL.BASE_URL}
        actions:
          enabled: true
          provisioning:
            enabled: true
          statefulset:
            actRunner: 
              config: |
                log:
                  level: debug
                cache:
                  enabled: false
                runner:
                  labels:
                    - "ubuntu-latest:docker://node:18.20-bullseye"
        redis-cluster:
          enabled: false
        redis:
          enabled: true
        postgresql-ha:
          enabled: false
        postgresql:
          enabled: true
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: gitea/routes
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: gitea/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false