apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: infra-project
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.26.2
      helm:
        parameters:
        - name: global.platform
          value: microk8s
        - name: pilot.env.PILOT_ENABLE_ALPHA_GATEWAY_API
          value: "true"
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.26.2
      helm:
        parameters:
          # - name: profile
          #   value: ambient
          - name: global.platform
            value: microk8s
          - name: pilot.env.PILOT_ENABLE_ALPHA_GATEWAY_API
            value: "true"
          - name: meshConfig.enableTracing
            value: "true"
          - name: meshConfig.extensionProviders.name
            value: otel-tracing
          - name: meshConfig.extensionProviders.opentelemetry.service
            value: alloy.alloy.svc.cluster.local
          - name: meshConfig.extensionProviders.opentelemetry.port
            value: "4317"
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: cni
      targetRevision: 1.26.2
      helm:
        parameters:
          # - name: profile
          #   value: ambient
          - name: global.platform
            value: microk8s
          - name: pilot.env.PILOT_ENABLE_ALPHA_GATEWAY_API
            value: "true"
    # - repoURL: https://istio-release.storage.googleapis.com/charts
    #   chart: ztunnel
    #   targetRevision: 1.26.2
    #   helm:
    #     parameters:
    #       - name: global.platform
    #         value: microk8s
    #       - name: pilot.env.PILOT_ENABLE_ALPHA_GATEWAY_API
    #         value: "true"
    - repoURL: "http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git"
      targetRevision: HEAD
      path: istio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true