apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "kiali"
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: 'https://kiali.org/helm-charts'
    chart: kiali-server
    targetRevision: 2.4.0
    helm:
      valueFiles:
      - $values/kiali/values.yaml
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: kiali
    ref: values
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: kiali/routes
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false