apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "openproject"
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: 'https://charts.openproject.org'
    chart: openproject
    targetRevision: 9.7.2
    helm:
      valueFiles:
      - $values/openproject/values.yaml
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: openproject
    ref: values
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: openproject/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: openproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false