apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "vault-secrets-operator"
  namespace: argocd
spec:
  project: infra-project
  sources:
  - repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault-secrets-operator
    targetRevision: 0.9.1
    helm:
      valueFiles:
      - $values/vault-secrets-operator/values.yaml
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: vault-secrets-operator
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false