apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "vault"
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.29.1
    helm:
      valueFiles:
      - $values/vault/values.yaml
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: vault
    ref: values
  - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/${APPLICATIONS.GITEA.ADMIN.USERNAME}/infra.git'
    targetRevision: HEAD
    path: vault/routes
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false