apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nats
  namespace: nats
spec:
  parentRefs:
    - group: gateway.networking.k8s.io	
      kind: Gateway	
      name: infra-gateway
      namespace: istio-system
  hostnames:
    - nats.${APPLICATIONS.GLOBAL.BASE_URL}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
       - kind: Service	
         name: nats-nui
         port: 31311
         weight: 100
         group: ''