apiVersion: v1
kind: Namespace
metadata:
  name: ittools
  labels:
    name: ittools
    istio.io/dataplane-mode: ambient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: ittools
  labels:
    app.kubernetes.io/name: it-tools
    app.kubernetes.io/version: "1.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: it-tools
      app.kubernetes.io/version: "1.0"
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: it-tools
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - name: it-tools
          image: corentinth/it-tools
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools-service
  namespace: ittools
spec:
  selector:
    app.kubernetes.io/name: it-tools
    app.kubernetes.io/version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
