apiVersion: v1
kind: Namespace
metadata:
  name: ittools
  labels:
    name: ittools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: ittools
  labels:
    app: it-tools
spec:
  selector:
    matchLabels:
      app: it-tools
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
        - name: it-tools
          image: corentinth/it-tools
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools-service
  namespace: ittools
spec:
  selector:
    app: it-tools
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
