grafana:
  namespaceOverride: grafana
  additionalDataSources:
    - name: loki
      basicAuth: false
      editable: false
      type: loki
      url: http://loki-gateway.loki.svc.cluster.local
      jsonData:
        httpHeaderName1: 'X-Scope-OrgID'
      secureJsonData:
        httpHeaderValue1: '${APPLICATIONS.GRAFANA.HEADER_VALUE}'
    - name: tempo
      basicAuth: false
      editable: true
      type: tempo
      url: http://tempo.tempo.svc.cluster.local:3100
      jsonData:
        httpMethod: GET
        tracesToLogsV2:
          datasourceUid: 'loki'
          spanStartTimeShift: '-10m'
          spanEndTimeShift: '10m'
          tags: [{key: 'job', value: 'job'}]
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: '{$${__tags}} |="$${__span.traceId}"'
        tracesToMetrics:
          datasourceUid: 'prometheus'
          spanStartTimeShift: '1h'
          spanEndTimeShift: '-1h'
          tags: [{key: 'service.name', value: 'service'}, {key: 'job'}]
          queries:
            - name: 'Sample Query'
              query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
