apiVersion: v1
kind: Service
metadata:
  name: openproject-postgres
  namespace: openproject
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: openproject
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        securityContext:
          privileged: false
        env:
        - name: POSTGRES_USER
          value: openproject
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: openproject-postgresql
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: openproject-postgres-data
---
apiVersion: v1
data:
  password: S3NXTVA4NldnRg==
  postgres-password: S3NXTVA4NldnRg==
kind: Secret
metadata:
  name: openproject-postgresql
  namespace: openproject
type: Opaque