kind: PersistentVolume
apiVersion: v1
metadata:
  name: openproject-postgres-data
  namespace: openproject
  labels:
    type: local
    app: openproject
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-postgres-data
  namespace: openproject
  labels:
    app: openproject
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi