kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: http://127.0.0.1:9999
          name: ${APPLICATIONS.BACKSTAGE.CLUSTER_NAME}
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
